version: '3.8'

services:
  todoapi:
    build:
      context: ./TodoApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=todoapi;Username=todouser;Password=todopass123
    depends_on:
      - postgres
    networks:
      - todo-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=todoapi
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge